name: Send Mail
on: push

jobs:
  mail:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "hello world"

      - name: Sending a mail
        if: ${{always()}}
        uses: dawidd6/action-send-mail@v3
        with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{secrets.MAIL_USERNAME}}
            password: ${{secrets.MAIL_PASSWORD}}
            subject: Github Actions job result
            to: javeedmeeran44@gmail.com
            from: Javv=ee # <user@example.com>
            body: Build job of ${{github.repository}} completed successfully!